version: "3.9"

services:
  web:
    container_name: webMirror
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "4545:80"
    depends_on:
      - rabbitmq
    networks:
      mirror_network:
        ipv4_address: 192.168.1.100
  mariadb:
    image: mariadb:5.5
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mirror
      MYSQL_DATABASE: mirror
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mirror_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mirror
    ports:
      - "3333:80"
    depends_on:
      - mariadb
    networks:
      - mirror_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mirror_network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    environment:
      - SWAGGER_JSON=/swagger/swagger.json
    volumes:
      - ./public/swagger:/swagger
    ports:
      - "4550:8080"
    depends_on:
      - web
    networks:
      - mirror_network

networks:
  mirror_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
